blank_issues_enabled: false
contact_links:
  - name: ðŸ“˜ Synack Documentation
    url: https://scottoffen.github.io/Synack
    about: Start here. Many questions are answered in the official docs.
  - name: ðŸ’¬ Community Discussions
    url: https://github.com/scottoffen/Synack/discussions
    about: Propose ideas, ask how-to questions, and get community help.
  - name: ðŸ™‹ StackOverflow #Synack
    url: https://stackoverflow.com/questions/tagged/Synack?sort=newest
    about: Ask/answer usage questions with the Synack tag.